"""Telemetry sanitizer — fixed-policy masker for outbound telemetry.

Sanitizes user-supplied strings before they leave the process as LLM requests,
MCP tool payloads, or externally-visible log lines. Pure function: no I/O,
no environment, no clock. The same input yields the same output, and the
alias map is per-instance.

Replacement strategy
--------------------

Four identifier categories are masked:

1. Private IPv4 — `10/8`, `172.16/12`, `192.168/16`, `127/8`
2. MAC addresses — IEEE 802 MAC, colon or hyphen delimited
3. Serial numbers — vendor-agnostic alphanumeric (uppercase, hyphens)
4. Hostnames — multi-label DNS names (heuristic)

Each match is replaced by a stable synthetic alias of the form
``<CATEGORY_PREFIX><SUFFIX>`` where ``SUFFIX`` is generated by an internal
counter (alphabetical for letters, zero-padded for digits). The alias map is
maintained per-instance so the same literal always maps to the same alias
within a session, and distinct literals map to distinct aliases.

Out of scope
------------

- API keys / tokens / credentials — handled by `secure-configuration` upstream.
- Public IPv4 addresses — allowed to leave the process.
- Validation that the input is "safe" — the sanitizer does not interpret
  meaning, only applies a fixed regex sweep.
"""

from __future__ import annotations

import logging
import re
from collections import OrderedDict
from dataclasses import dataclass
from typing import Final

logger = logging.getLogger(__name__)


class SanitizerInputError(TypeError):
    """Raised when the sanitizer receives a non-string input."""


@dataclass(frozen=True)
class SanitizedText:
    """Result of a sanitize() call."""

    text: str
    counts: dict[str, int]  # {"ip", "mac", "serial", "hostname"}


# ---------------------------------------------------------------------------
# Module-level regex patterns. Compile once, reuse forever.
# ---------------------------------------------------------------------------

IPV4_PRIVATE_REGEX: Final[re.Pattern[str]] = re.compile(
    r"(?<![0-9.])(?:"
    r"10\.\d{1,3}\.\d{1,3}\.\d{1,3}"  # 10/8
    r"|172\.(?:1[6-9]|2\d|3[01])\.\d{1,3}\.\d{1,3}"  # 172.16/12
    r"|192\.168\.\d{1,3}\.\d{1,3}"  # 192.168/16
    r"|127\.\d{1,3}\.\d{1,3}\.\d{1,3}"  # 127/8
    r")(?![0-9.])"
)

MAC_REGEX: Final[re.Pattern[str]] = re.compile(
    r"(?<![0-9A-Fa-f])(?:[0-9A-Fa-f]{2}[:-]){5}[0-9A-Fa-f]{2}(?![0-9A-Fa-f])"
)

# Vendor-agnostic serial pattern: starts with at least two uppercase
# alphanumerics, optionally followed by additional uppercase / hyphen chars,
# ending with an uppercase alphanumeric. Total length ≥ 8.
SERIAL_REGEX: Final[re.Pattern[str]] = re.compile(
    r"(?<![A-Za-z0-9-])[A-Z0-9]{2}[A-Z0-9-]{4,}[A-Z0-9](?![A-Za-z0-9-])"
)

# Hostname: lowercase labels joined by dots. First label starts with
# [a-z0-9], subsequent labels start with [a-z0-9-]. Final label ≥ 2 chars.
HOSTNAME_REGEX: Final[re.Pattern[str]] = re.compile(
    r"(?<![A-Za-z0-9.-])"
    r"(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+"
    r"[a-z]{2,63}"
    r"(?![A-Za-z0-9.-])"
)


# ---------------------------------------------------------------------------
# Alias generator — distinct prefix per category, deterministic per-instance.
# ---------------------------------------------------------------------------

_LETTER_ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"


def _alpha_suffix(index: int) -> str:
    """Index 0 -> 'A', 1 -> 'B', ..., 25 -> 'Z', 26 -> 'AA', 27 -> 'AB', ..."""
    if index < 26:
        return _LETTER_ALPHABET[index]
    # Two-letter combination for index >= 26 (kept simple; > 676 literals is rare).
    first, second = divmod(index, 26)
    return _LETTER_ALPHABET[first - 1] + _LETTER_ALPHABET[second]


def _numeric_suffix(index: int) -> str:
    """Index 0 -> '01', 1 -> '02', ..., 99 -> '100', 100 -> '101', ..."""
    return f"{index + 1:02d}"


# ---------------------------------------------------------------------------
# Sanitizer — stateful alias map, otherwise pure.
# ---------------------------------------------------------------------------


class Sanitizer:
    """Fixed-policy masker for outbound telemetry strings.

    Hold one instance per session to keep the alias map stable for the
    session's lifetime; a new instance starts a fresh map.
    """

    def __init__(self) -> None:
        # OrderedDict gives deterministic iteration order in logs / debugging.
        self._alias_map: dict[str, dict[str, str]] = {
            "ip": OrderedDict(),
            "mac": OrderedDict(),
            "serial": OrderedDict(),
            "hostname": OrderedDict(),
        }

    # -- internal helpers -----------------------------------------------------

    def _alias_for(self, category: str, literal: str) -> str:
        """Return the alias for `literal` in `category`, creating one if needed."""
        bucket = self._alias_map[category]
        if literal in bucket:
            return bucket[literal]

        idx = len(bucket)
        if category == "ip":
            alias = f"RADIO_NODE_{_alpha_suffix(idx)}"
        elif category == "mac":
            alias = f"SWITCH_ACC_{_numeric_suffix(idx)}"
        elif category == "serial":
            alias = f"SERIAL_{_alpha_suffix(idx)}"
        elif category == "hostname":
            alias = f"HOST_{_alpha_suffix(idx)}"
        else:  # pragma: no cover - defensive
            alias = f"ALIAS_{category.upper()}_{idx}"
        bucket[literal] = alias
        logger.debug("alias %s=%s", literal, alias)
        return alias

    @staticmethod
    def _replace_category(
        text: str, pattern: re.Pattern[str], category: str, sanitizer: "Sanitizer"
    ) -> tuple[str, int]:
        """Replace each `pattern` match with a stable alias; return text + count."""

        def sub(match: re.Match[str]) -> str:
            return sanitizer._alias_for(category, match.group(0))

        new_text, count = pattern.subn(sub, text)
        return new_text, count

    # -- public API -----------------------------------------------------------

    def sanitize(self, text: str) -> SanitizedText:
        """Replace all four identifier categories with stable aliases.

        Raises `SanitizerInputError` if `text` is not a string.
        """
        if not isinstance(text, str):
            raise SanitizerInputError(
                f"Sanitizer.sanitize() expects str; got {type(text).__name__}"
            )

        text, ip_count = self._replace_category(text, IPV4_PRIVATE_REGEX, "ip", self)
        text, mac_count = self._replace_category(text, MAC_REGEX, "mac", self)
        text, serial_count = self._replace_category(text, SERIAL_REGEX, "serial", self)
        text, hostname_count = self._replace_category(text, HOSTNAME_REGEX, "hostname", self)

        return SanitizedText(
            text=text,
            counts={
                "ip": ip_count,
                "mac": mac_count,
                "serial": serial_count,
                "hostname": hostname_count,
            },
        )


__all__ = [
    "Sanitizer",
    "SanitizedText",
    "SanitizerInputError",
    "IPV4_PRIVATE_REGEX",
    "MAC_REGEX",
    "SERIAL_REGEX",
    "HOSTNAME_REGEX",
]
